module.exports={
  devServer:{
    proxy:{
      '/ajax':{
        target:'https://m.maoyan.com',
        secure:true,
        changeOrigin:true
      },
      '/dianying':{
        target:'https://m.maoyan.com',
        secure:true,
        changeOrigin:true
      },
    }
  }
}